# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e850ac34040817d9419db50c6c3f30596b4d2dc14327b8e79d7879576a4be423a8b25581e00cc4543d3c2de8a320c1e7e92ecb4a564b3afdbc9994769416b286

test:
  secret_key_base: c70930a136d2081ccf9188f34baa105727ac759ca3b2c6250d96bbcaa6516bf170204d7ae6031ad18de3343c1462682af581393770651e397dbe18ae677e43c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
